// Country positions (approximate center coordinates for label placement)
// Using longitude, latitude format for react-simple-maps
export const europeanCountries = {
  // Country code: { name: English name, coordinates: [lng, lat] }
  PT: { name: "Portugal", coordinates: [-8.2, 39.5] },
  ES: { name: "Spain", coordinates: [-3.7, 40.4] },
  FR: { name: "France", coordinates: [2.3, 46.6] },
  BE: { name: "Belgium", coordinates: [4.4, 50.8] },
  NL: { name: "Netherlands", coordinates: [5.3, 52.1] },
  DE: { name: "Germany", coordinates: [10.4, 51.2] },
  CH: { name: "Switzerland", coordinates: [8.2, 46.8] },
  AT: { name: "Austria", coordinates: [14.5, 47.5] },
  IT: { name: "Italy", coordinates: [12.6, 42.5] },
  SI: { name: "Slovenia", coordinates: [14.9, 46.1] },
  HR: { name: "Croatia", coordinates: [15.9, 45.1] },
  BA: { name: "Bosnia", coordinates: [17.7, 43.9] },
  RS: { name: "Serbia", coordinates: [21.0, 44.0] },
  ME: { name: "Montenegro", coordinates: [19.3, 42.7] },
  AL: { name: "Albania", coordinates: [20.1, 41.3] },
  MK: { name: "North Macedonia", coordinates: [21.7, 41.5] },
  GR: { name: "Greece", coordinates: [22.0, 39.0] },
  BG: { name: "Bulgaria", coordinates: [25.5, 42.7] },
  RO: { name: "Romania", coordinates: [25.0, 45.9] },
  MD: { name: "Moldova", coordinates: [28.8, 47.0] },
  UA: { name: "Ukraine", coordinates: [32.0, 49.0] },
  BY: { name: "Belarus", coordinates: [28.0, 53.5] },
  PL: { name: "Poland", coordinates: [19.1, 52.0] },
  CZ: { name: "Czechia", coordinates: [15.5, 49.8] },
  SK: { name: "Slovakia", coordinates: [19.5, 48.7] },
  HU: { name: "Hungary", coordinates: [19.5, 47.2] },
  LT: { name: "Lithuania", coordinates: [24.0, 55.2] },
  LV: { name: "Latvia", coordinates: [24.6, 56.9] },
  EE: { name: "Estonia", coordinates: [25.0, 58.6] },
  FI: { name: "Finland", coordinates: [26.0, 64.0] },
  SE: { name: "Sweden", coordinates: [18.6, 62.0] },
  NO: { name: "Norway", coordinates: [8.5, 62.0] },
  DK: { name: "Denmark", coordinates: [9.5, 56.0] },
  IE: { name: "Ireland", coordinates: [-8.0, 53.4] },
  GB: { name: "United Kingdom", coordinates: [-2.0, 54.0] },
  IS: { name: "Iceland", coordinates: [-19.0, 65.0] },
  RU: { name: "Russia", coordinates: [40.0, 56.0] },
  TR: { name: "Turkey", coordinates: [35.0, 39.0] },
  CY: { name: "Cyprus", coordinates: [33.4, 35.1] },
  MT: { name: "Malta", coordinates: [14.4, 35.9] },
  LU: { name: "Luxembourg", coordinates: [6.1, 49.8] },
  XK: { name: "Kosovo", coordinates: [20.9, 42.6] },
};

// Translations of country names in different European languages
// Key: Country code (which country's name we're translating)
// Value: Object with language codes as keys and translations as values
export const countryTranslations = {
  DE: { // Germany in different languages
    PT: "Alemanha",
    ES: "Alemania",
    FR: "Allemagne",
    BE: "Allemagne",
    NL: "Duitsland",
    DE: "Deutschland",
    CH: "Deutschland",
    AT: "Deutschland",
    IT: "Germania",
    SI: "Nemčija",
    HR: "Njemačka",
    BA: "Njemačka",
    RS: "Nemačka",
    ME: "Njemačka",
    AL: "Gjermania",
    MK: "Германија",
    GR: "Γερμανία",
    BG: "Германия",
    RO: "Germania",
    MD: "Germania",
    UA: "Німеччина",
    BY: "Нямеччына",
    PL: "Niemcy",
    CZ: "Německo",
    SK: "Nemecko",
    HU: "Németország",
    LT: "Vokietija",
    LV: "Vācija",
    EE: "Saksamaa",
    FI: "Saksa",
    SE: "Tyskland",
    NO: "Tyskland",
    DK: "Tyskland",
    IE: "An Ghearmáin",
    GB: "Germany",
    IS: "Þýskaland",
    RU: "Германия",
    TR: "Almanya",
    CY: "Γερμανία",
    MT: "Il-Ġermanja",
    LU: "Däitschland",
    XK: "Gjermania",
  },
  RO: { // Romania in different languages
    PT: "Roménia",
    ES: "Rumania",
    FR: "Roumanie",
    BE: "Roumanie",
    NL: "Roemenië",
    DE: "Rumänien",
    CH: "Rumänien",
    AT: "Rumänien",
    IT: "Romania",
    SI: "Romunija",
    HR: "Rumunjska",
    BA: "Rumunija",
    RS: "Румунија",
    ME: "Rumunija",
    AL: "Rumania",
    MK: "Романија",
    GR: "Ρουμανία",
    BG: "Румъния",
    RO: "România",
    MD: "România",
    UA: "Румунія",
    BY: "Румынія",
    PL: "Rumunia",
    CZ: "Rumunsko",
    SK: "Rumunsko",
    HU: "Románia",
    LT: "Rumunija",
    LV: "Rumānija",
    EE: "Rumeenia",
    FI: "Romania",
    SE: "Rumänien",
    NO: "Romania",
    DK: "Rumænien",
    IE: "An Rómáin",
    GB: "Romania",
    IS: "Rúmenía",
    RU: "Румыния",
    TR: "Romanya",
    CY: "Ρουμανία",
    MT: "Ir-Rumanija",
    LU: "Rumänien",
    XK: "Rumania",
  },
  GB: { // United Kingdom in different languages
    PT: "Reino Unido",
    ES: "Reino Unido",
    FR: "Royaume-Uni",
    BE: "Royaume-Uni",
    NL: "Verenigd Koninkrijk",
    DE: "Vereinigtes Königreich",
    CH: "Vereinigtes Königreich",
    AT: "Vereinigtes Königreich",
    IT: "Regno Unito",
    SI: "Združeno kraljestvo",
    HR: "Ujedinjeno Kraljevstvo",
    BA: "Ujedinjeno Kraljevstvo",
    RS: "Ujedinjeno Kraljevstvo",
    ME: "Ujedinjeno Kraljevstvo",
    AL: "Mbretëria e Bashkuar",
    MK: "Обединето Кралство",
    GR: "Ηνωμένο Βασίλειο",
    BG: "Обединеното кралство",
    RO: "Marea Britanie",
    MD: "Marea Britanie",
    UA: "Велика Британія",
    BY: "Вялікабрытанія",
    PL: "Wielka Brytania",
    CZ: "Spojené království",
    SK: "Spojené kráľovstvo",
    HU: "Egyesült Királyság",
    LT: "Jungtinė Karalystė",
    LV: "Apvienotā Karaliste",
    EE: "Ühendkuningriik",
    FI: "Yhdistynyt kuningaskunta",
    SE: "Storbritannien",
    NO: "Storbritannia",
    DK: "Storbritannien",
    IE: "An Ríocht Aontaithe",
    GB: "United Kingdom",
    IS: "Bretland",
    RU: "Великобритания",
    TR: "Birleşik Krallık",
    CY: "Ηνωμένο Βασίλειο",
    MT: "Ir-Renju Unit",
    LU: "Vereenegt Kinnekräich",
    XK: "Mbretëria e Bashkuar",
  },
  FR: { // France in different languages
    PT: "França",
    ES: "Francia",
    FR: "France",
    BE: "France",
    NL: "Frankrijk",
    DE: "Frankreich",
    CH: "Frankreich",
    AT: "Frankreich",
    IT: "Francia",
    SI: "Francija",
    HR: "Francuska",
    BA: "Francuska",
    RS: "Francuska",
    ME: "Francuska",
    AL: "Franca",
    MK: "Франција",
    GR: "Γαλλία",
    BG: "Франция",
    RO: "Franța",
    MD: "Franța",
    UA: "Франція",
    BY: "Францыя",
    PL: "Francja",
    CZ: "Francie",
    SK: "Francúzsko",
    HU: "Franciaország",
    LT: "Prancūzija",
    LV: "Francija",
    EE: "Prantsusmaa",
    FI: "Ranska",
    SE: "Frankrike",
    NO: "Frankrike",
    DK: "Frankrig",
    IE: "An Fhrainc",
    GB: "France",
    IS: "Frakkland",
    RU: "Франция",
    TR: "Fransa",
    CY: "Γαλλία",
    MT: "Franza",
    LU: "Frankräich",
    XK: "Franca",
  },
  ES: { // Spain in different languages
    PT: "Espanha",
    ES: "España",
    FR: "Espagne",
    BE: "Espagne",
    NL: "Spanje",
    DE: "Spanien",
    CH: "Spanien",
    AT: "Spanien",
    IT: "Spagna",
    SI: "Španija",
    HR: "Španjolska",
    BA: "Španija",
    RS: "Španija",
    ME: "Španija",
    AL: "Spanja",
    MK: "Шпанија",
    GR: "Ισπανία",
    BG: "Испания",
    RO: "Spania",
    MD: "Spania",
    UA: "Іспанія",
    BY: "Іспанія",
    PL: "Hiszpania",
    CZ: "Španělsko",
    SK: "Španielsko",
    HU: "Spanyolország",
    LT: "Ispanija",
    LV: "Spānija",
    EE: "Hispaania",
    FI: "Espanja",
    SE: "Spanien",
    NO: "Spania",
    DK: "Spanien",
    IE: "An Spáinn",
    GB: "Spain",
    IS: "Spánn",
    RU: "Испания",
    TR: "İspanya",
    CY: "Ισπανία",
    MT: "Spanja",
    LU: "Spuenien",
    XK: "Spanja",
  },
  IT: { // Italy in different languages
    PT: "Itália",
    ES: "Italia",
    FR: "Italie",
    BE: "Italie",
    NL: "Italië",
    DE: "Italien",
    CH: "Italien",
    AT: "Italien",
    IT: "Italia",
    SI: "Italija",
    HR: "Italija",
    BA: "Italija",
    RS: "Italija",
    ME: "Italija",
    AL: "Itali",
    MK: "Италија",
    GR: "Ιταλία",
    BG: "Италия",
    RO: "Italia",
    MD: "Italia",
    UA: "Італія",
    BY: "Італія",
    PL: "Włochy",
    CZ: "Itálie",
    SK: "Taliansko",
    HU: "Olaszország",
    LT: "Italija",
    LV: "Itālija",
    EE: "Itaalia",
    FI: "Italia",
    SE: "Italien",
    NO: "Italia",
    DK: "Italien",
    IE: "An Iodáil",
    GB: "Italy",
    IS: "Ítalía",
    RU: "Италия",
    TR: "İtalya",
    CY: "Ιταλία",
    MT: "Italja",
    LU: "Italien",
    XK: "Italia",
  },
  GR: { // Greece in different languages
    PT: "Grécia",
    ES: "Grecia",
    FR: "Grèce",
    BE: "Grèce",
    NL: "Griekenland",
    DE: "Griechenland",
    CH: "Griechenland",
    AT: "Griechenland",
    IT: "Grecia",
    SI: "Grčija",
    HR: "Grčka",
    BA: "Grčka",
    RS: "Grčka",
    ME: "Grčka",
    AL: "Greqi",
    MK: "Грција",
    GR: "Ελλάδα",
    BG: "Гърция",
    RO: "Grecia",
    MD: "Grecia",
    UA: "Греція",
    BY: "Грэцыя",
    PL: "Grecja",
    CZ: "Řecko",
    SK: "Grécko",
    HU: "Görögország",
    LT: "Graikija",
    LV: "Grieķija",
    EE: "Kreeka",
    FI: "Kreikka",
    SE: "Grekland",
    NO: "Hellas",
    DK: "Grækenland",
    IE: "An Ghréig",
    GB: "Greece",
    IS: "Grikkland",
    RU: "Греция",
    TR: "Yunanistan",
    CY: "Ελλάδα",
    MT: "Greċja",
    LU: "Griicheland",
    XK: "Greqia",
  },
  PL: { // Poland in different languages
    PT: "Polónia",
    ES: "Polonia",
    FR: "Pologne",
    BE: "Pologne",
    NL: "Polen",
    DE: "Polen",
    CH: "Polen",
    AT: "Polen",
    IT: "Polonia",
    SI: "Poljska",
    HR: "Poljska",
    BA: "Poljska",
    RS: "Poljska",
    ME: "Poljska",
    AL: "Poloni",
    MK: "Полска",
    GR: "Πολωνία",
    BG: "Полша",
    RO: "Polonia",
    MD: "Polonia",
    UA: "Польща",
    BY: "Польшча",
    PL: "Polska",
    CZ: "Polsko",
    SK: "Poľsko",
    HU: "Lengyelország",
    LT: "Lenkija",
    LV: "Polija",
    EE: "Poola",
    FI: "Puola",
    SE: "Polen",
    NO: "Polen",
    DK: "Polen",
    IE: "An Pholainn",
    GB: "Poland",
    IS: "Pólland",
    RU: "Польша",
    TR: "Polonya",
    CY: "Πολωνία",
    MT: "Polonja",
    LU: "Polen",
    XK: "Polonia",
  },
  NL: { // Netherlands in different languages
    PT: "Países Baixos",
    ES: "Países Bajos",
    FR: "Pays-Bas",
    BE: "Pays-Bas",
    NL: "Nederland",
    DE: "Niederlande",
    CH: "Niederlande",
    AT: "Niederlande",
    IT: "Paesi Bassi",
    SI: "Nizozemska",
    HR: "Nizozemska",
    BA: "Nizozemska",
    RS: "Holandija",
    ME: "Holandija",
    AL: "Holandë",
    MK: "Холандија",
    GR: "Ολλανδία",
    BG: "Нидерландия",
    RO: "Țările de Jos",
    MD: "Țările de Jos",
    UA: "Нідерланди",
    BY: "Нідэрланды",
    PL: "Holandia",
    CZ: "Nizozemsko",
    SK: "Holandsko",
    HU: "Hollandia",
    LT: "Nyderlandai",
    LV: "Nīderlande",
    EE: "Holland",
    FI: "Alankomaat",
    SE: "Nederländerna",
    NO: "Nederland",
    DK: "Nederlandene",
    IE: "An Ísiltír",
    GB: "Netherlands",
    IS: "Holland",
    RU: "Нидерланды",
    TR: "Hollanda",
    CY: "Ολλανδία",
    MT: "Pajjiżi l-Baxxi",
    LU: "Holland",
    XK: "Holanda",
  },
  IE: { // Ireland in different languages
    PT: "Irlanda",
    ES: "Irlanda",
    FR: "Irlande",
    BE: "Irlande",
    NL: "Ierland",
    DE: "Irland",
    CH: "Irland",
    AT: "Irland",
    IT: "Irlanda",
    SI: "Irska",
    HR: "Irska",
    BA: "Irska",
    RS: "Irska",
    ME: "Irska",
    AL: "Irlanda",
    MK: "Ирска",
    GR: "Ιρλανδία",
    BG: "Ирландия",
    RO: "Irlanda",
    MD: "Irlanda",
    UA: "Ірландія",
    BY: "Ірландыя",
    PL: "Irlandia",
    CZ: "Irsko",
    SK: "Írsko",
    HU: "Írország",
    LT: "Airija",
    LV: "Īrija",
    EE: "Iirimaa",
    FI: "Irlanti",
    SE: "Irland",
    NO: "Irland",
    DK: "Irland",
    IE: "Éire",
    GB: "Ireland",
    IS: "Írland",
    RU: "Ирландия",
    TR: "İrlanda",
    CY: "Ιρλανδία",
    MT: "Irlanda",
    LU: "Irland",
    XK: "Irlanda",
  },
  BE: { // Belgium in different languages
    PT: "Bélgica",
    ES: "Bélgica",
    FR: "Belgique",
    BE: "Belgique",
    NL: "België",
    DE: "Belgien",
    CH: "Belgien",
    AT: "Belgien",
    IT: "Belgio",
    SI: "Belgija",
    HR: "Belgija",
    BA: "Belgija",
    RS: "Belgija",
    ME: "Belgija",
    AL: "Belgjika",
    MK: "Белгија",
    GR: "Βέλγιο",
    BG: "Белгия",
    RO: "Belgia",
    MD: "Belgia",
    UA: "Бельгія",
    BY: "Бельгія",
    PL: "Belgia",
    CZ: "Belgie",
    SK: "Belgicko",
    HU: "Belgium",
    LT: "Belgija",
    LV: "Beļģija",
    EE: "Belgia",
    FI: "Belgia",
    SE: "Belgien",
    NO: "Belgia",
    DK: "Belgien",
    IE: "An Bheilg",
    GB: "Belgium",
    IS: "Belgía",
    RU: "Бельгия",
    TR: "Belçika",
    CY: "Βέλγιο",
    MT: "Belġju",
    LU: "Belsch",
    XK: "Belgjika",
  },
  LU: { // Luxembourg in different languages
    PT: "Luxemburgo",
    ES: "Luxemburgo",
    FR: "Luxembourg",
    BE: "Luxembourg",
    NL: "Luxemburg",
    DE: "Luxemburg",
    CH: "Luxemburg",
    AT: "Luxemburg",
    IT: "Lussemburgo",
    SI: "Luksemburg",
    HR: "Luksemburg",
    BA: "Luksemburg",
    RS: "Luksemburg",
    ME: "Luksemburg",
    AL: "Luksemburg",
    MK: "Луксембург",
    GR: "Λουξεμβούργο",
    BG: "Люксембург",
    RO: "Luxemburg",
    MD: "Luxemburg",
    UA: "Люксембург",
    BY: "Люксембург",
    PL: "Luksemburg",
    CZ: "Lucembursko",
    SK: "Luxembursko",
    HU: "Luxemburg",
    LT: "Liuksemburgas",
    LV: "Luksemburga",
    EE: "Luksemburg",
    FI: "Luxemburg",
    SE: "Luxemburg",
    NO: "Luxembourg",
    DK: "Luxembourg",
    IE: "Lucsamburg",
    GB: "Luxembourg",
    IS: "Lúxemborg",
    RU: "Люксембург",
    TR: "Lüksemburg",
    CY: "Λουξεμβούργο",
    MT: "Lussemburgu",
    LU: "Lëtzebuerg",
    XK: "Luksemburgu",
  },
};

// Function to find country by name (case-insensitive, partial match)
export function findCountryByName(searchTerm) {
  const term = searchTerm.toLowerCase().trim();
  if (!term) return null;

  // First check English names
  for (const [code, data] of Object.entries(europeanCountries)) {
    if (data.name.toLowerCase().includes(term)) {
      return code;
    }
  }

  // Then check translations
  for (const [countryCode, translations] of Object.entries(countryTranslations)) {
    for (const translation of Object.values(translations)) {
      if (translation.toLowerCase().includes(term)) {
        return countryCode;
      }
    }
  }

  return null;
}

// Get all translations for a country code
export function getTranslationsForCountry(countryCode) {
  return countryTranslations[countryCode] || null;
}
