// Country positions (approximate center coordinates for label placement)
// Using longitude, latitude format for react-simple-maps
export const europeanCountries = {
  // Country code: { name: English name, coordinates: [lng, lat] }
  PT: { name: "Portugal", coordinates: [-8.2, 39.5] },
  ES: { name: "Spain", coordinates: [-3.7, 40.4] },
  FR: { name: "France", coordinates: [2.3, 46.6] },
  AD: { name: "Andorra", coordinates: [1.5, 42.5] },
  BE: { name: "Belgium", coordinates: [4.4, 50.8] },
  NL: { name: "Netherlands", coordinates: [5.3, 52.1] },
  DE: { name: "Germany", coordinates: [10.4, 51.2] },
  LI: { name: "Liechtenstein", coordinates: [9.55, 47.15] },
  CH: { name: "Switzerland", coordinates: [8.2, 46.8] },
  AT: { name: "Austria", coordinates: [14.5, 47.5] },
  IT: { name: "Italy", coordinates: [12.6, 42.5] },
  MC: { name: "Monaco", coordinates: [7.4, 43.75] },
  SM: { name: "San Marino", coordinates: [12.45, 43.95] },
  VA: { name: "Vatican City", coordinates: [12.45, 41.9] },
  SI: { name: "Slovenia", coordinates: [14.9, 46.1] },
  HR: { name: "Croatia", coordinates: [15.9, 45.1] },
  BA: { name: "Bosnia and Herzegovina", coordinates: [17.7, 43.9] },
  RS: { name: "Serbia", coordinates: [21.0, 44.0] },
  ME: { name: "Montenegro", coordinates: [19.3, 42.7] },
  AL: { name: "Albania", coordinates: [20.1, 41.3] },
  MK: { name: "North Macedonia", coordinates: [21.7, 41.5] },
  GR: { name: "Greece", coordinates: [22.0, 39.0] },
  BG: { name: "Bulgaria", coordinates: [25.5, 42.7] },
  RO: { name: "Romania", coordinates: [25.0, 45.9] },
  MD: { name: "Moldova", coordinates: [28.8, 47.0] },
  UA: { name: "Ukraine", coordinates: [32.0, 49.0] },
  BY: { name: "Belarus", coordinates: [28.0, 53.5] },
  PL: { name: "Poland", coordinates: [19.1, 52.0] },
  CZ: { name: "Czechia", coordinates: [15.5, 49.8] },
  SK: { name: "Slovakia", coordinates: [19.5, 48.7] },
  HU: { name: "Hungary", coordinates: [19.5, 47.2] },
  LT: { name: "Lithuania", coordinates: [24.0, 55.2] },
  LV: { name: "Latvia", coordinates: [24.6, 56.9] },
  EE: { name: "Estonia", coordinates: [25.0, 58.6] },
  FI: { name: "Finland", coordinates: [26.0, 64.0] },
  SE: { name: "Sweden", coordinates: [18.6, 62.0] },
  NO: { name: "Norway", coordinates: [8.5, 62.0] },
  DK: { name: "Denmark", coordinates: [9.5, 56.0] },
  IE: { name: "Ireland", coordinates: [-8.0, 53.4] },
  GB: { name: "United Kingdom", coordinates: [-2.0, 54.0] },
  IS: { name: "Iceland", coordinates: [-19.0, 65.0] },
  RU: { name: "Russia", coordinates: [40.0, 56.0] },
  TR: { name: "Turkey", coordinates: [35.0, 39.0] },
  GE: { name: "Georgia", coordinates: [43.5, 42.1] },
  AM: { name: "Armenia", coordinates: [45.0, 40.1] },
  AZ: { name: "Azerbaijan", coordinates: [47.6, 40.3] },
  CY: { name: "Cyprus", coordinates: [33.4, 35.1] },
  MT: { name: "Malta", coordinates: [14.4, 35.9] },
  LU: { name: "Luxembourg", coordinates: [6.1, 49.8] },
  XK: { name: "Kosovo", coordinates: [20.9, 42.6] },
};

// Translations of country names in different European languages
// Key: Country code (which country's name we're translating)
// Value: Object with language codes as keys and translations as values
export const countryTranslations = {
  DE: { // Germany in different languages
    PT: "Alemanha",
    ES: "Alemania",
    FR: "Allemagne",
    BE: "Allemagne",
    NL: "Duitsland",
    DE: "Deutschland",
    CH: "Deutschland",
    AT: "Deutschland",
    IT: "Germania",
    SI: "Nemčija",
    HR: "Njemačka",
    BA: "Njemačka",
    RS: "Nemačka",
    ME: "Njemačka",
    AL: "Gjermania",
    MK: "Германија",
    GR: "Γερμανία",
    BG: "Германия",
    RO: "Germania",
    MD: "Germania",
    UA: "Німеччина",
    BY: "Нямеччына",
    PL: "Niemcy",
    CZ: "Německo",
    SK: "Nemecko",
    HU: "Németország",
    LT: "Vokietija",
    LV: "Vācija",
    EE: "Saksamaa",
    FI: "Saksa",
    SE: "Tyskland",
    NO: "Tyskland",
    DK: "Tyskland",
    IE: "An Ghearmáin",
    GB: "Germany",
    IS: "Þýskaland",
    RU: "Германия",
    TR: "Almanya",
    CY: "Γερμανία",
    MT: "Il-Ġermanja",
    LU: "Däitschland",
    XK: "Gjermania",
  },
  RO: { // Romania in different languages
    PT: "Roménia",
    ES: "Rumania",
    FR: "Roumanie",
    BE: "Roumanie",
    NL: "Roemenië",
    DE: "Rumänien",
    CH: "Rumänien",
    AT: "Rumänien",
    IT: "Romania",
    SI: "Romunija",
    HR: "Rumunjska",
    BA: "Rumunija",
    RS: "Румунија",
    ME: "Rumunija",
    AL: "Rumania",
    MK: "Романија",
    GR: "Ρουμανία",
    BG: "Румъния",
    RO: "România",
    MD: "România",
    UA: "Румунія",
    BY: "Румынія",
    PL: "Rumunia",
    CZ: "Rumunsko",
    SK: "Rumunsko",
    HU: "Románia",
    LT: "Rumunija",
    LV: "Rumānija",
    EE: "Rumeenia",
    FI: "Romania",
    SE: "Rumänien",
    NO: "Romania",
    DK: "Rumænien",
    IE: "An Rómáin",
    GB: "Romania",
    IS: "Rúmenía",
    RU: "Румыния",
    TR: "Romanya",
    CY: "Ρουμανία",
    MT: "Ir-Rumanija",
    LU: "Rumänien",
    XK: "Rumania",
  },
  GB: { // United Kingdom in different languages
    PT: "Reino Unido",
    ES: "Reino Unido",
    FR: "Royaume-Uni",
    BE: "Royaume-Uni",
    NL: "Verenigd Koninkrijk",
    DE: "Vereinigtes Königreich",
    CH: "Vereinigtes Königreich",
    AT: "Vereinigtes Königreich",
    IT: "Regno Unito",
    SI: "Združeno kraljestvo",
    HR: "Ujedinjeno Kraljevstvo",
    BA: "Ujedinjeno Kraljevstvo",
    RS: "Ujedinjeno Kraljevstvo",
    ME: "Ujedinjeno Kraljevstvo",
    AL: "Mbretëria e Bashkuar",
    MK: "Обединето Кралство",
    GR: "Ηνωμένο Βασίλειο",
    BG: "Обединеното кралство",
    RO: "Marea Britanie",
    MD: "Marea Britanie",
    UA: "Велика Британія",
    BY: "Вялікабрытанія",
    PL: "Wielka Brytania",
    CZ: "Spojené království",
    SK: "Spojené kráľovstvo",
    HU: "Egyesült Királyság",
    LT: "Jungtinė Karalystė",
    LV: "Apvienotā Karaliste",
    EE: "Ühendkuningriik",
    FI: "Yhdistynyt kuningaskunta",
    SE: "Storbritannien",
    NO: "Storbritannia",
    DK: "Storbritannien",
    IE: "An Ríocht Aontaithe",
    GB: "United Kingdom",
    IS: "Bretland",
    RU: "Великобритания",
    TR: "Birleşik Krallık",
    CY: "Ηνωμένο Βασίλειο",
    MT: "Ir-Renju Unit",
    LU: "Vereenegt Kinnekräich",
    XK: "Mbretëria e Bashkuar",
  },
  FR: { // France in different languages
    PT: "França",
    ES: "Francia",
    FR: "France",
    BE: "France",
    NL: "Frankrijk",
    DE: "Frankreich",
    CH: "Frankreich",
    AT: "Frankreich",
    IT: "Francia",
    SI: "Francija",
    HR: "Francuska",
    BA: "Francuska",
    RS: "Francuska",
    ME: "Francuska",
    AL: "Franca",
    MK: "Франција",
    GR: "Γαλλία",
    BG: "Франция",
    RO: "Franța",
    MD: "Franța",
    UA: "Франція",
    BY: "Францыя",
    PL: "Francja",
    CZ: "Francie",
    SK: "Francúzsko",
    HU: "Franciaország",
    LT: "Prancūzija",
    LV: "Francija",
    EE: "Prantsusmaa",
    FI: "Ranska",
    SE: "Frankrike",
    NO: "Frankrike",
    DK: "Frankrig",
    IE: "An Fhrainc",
    GB: "France",
    IS: "Frakkland",
    RU: "Франция",
    TR: "Fransa",
    CY: "Γαλλία",
    MT: "Franza",
    LU: "Frankräich",
    XK: "Franca",
  },
  ES: { // Spain in different languages
    PT: "Espanha",
    ES: "España",
    FR: "Espagne",
    BE: "Espagne",
    NL: "Spanje",
    DE: "Spanien",
    CH: "Spanien",
    AT: "Spanien",
    IT: "Spagna",
    SI: "Španija",
    HR: "Španjolska",
    BA: "Španija",
    RS: "Španija",
    ME: "Španija",
    AL: "Spanja",
    MK: "Шпанија",
    GR: "Ισπανία",
    BG: "Испания",
    RO: "Spania",
    MD: "Spania",
    UA: "Іспанія",
    BY: "Іспанія",
    PL: "Hiszpania",
    CZ: "Španělsko",
    SK: "Španielsko",
    HU: "Spanyolország",
    LT: "Ispanija",
    LV: "Spānija",
    EE: "Hispaania",
    FI: "Espanja",
    SE: "Spanien",
    NO: "Spania",
    DK: "Spanien",
    IE: "An Spáinn",
    GB: "Spain",
    IS: "Spánn",
    RU: "Испания",
    TR: "İspanya",
    CY: "Ισπανία",
    MT: "Spanja",
    LU: "Spuenien",
    XK: "Spanja",
  },
  IT: { // Italy in different languages
    PT: "Itália",
    ES: "Italia",
    FR: "Italie",
    BE: "Italie",
    NL: "Italië",
    DE: "Italien",
    CH: "Italien",
    AT: "Italien",
    IT: "Italia",
    SI: "Italija",
    HR: "Italija",
    BA: "Italija",
    RS: "Italija",
    ME: "Italija",
    AL: "Itali",
    MK: "Италија",
    GR: "Ιταλία",
    BG: "Италия",
    RO: "Italia",
    MD: "Italia",
    UA: "Італія",
    BY: "Італія",
    PL: "Włochy",
    CZ: "Itálie",
    SK: "Taliansko",
    HU: "Olaszország",
    LT: "Italija",
    LV: "Itālija",
    EE: "Itaalia",
    FI: "Italia",
    SE: "Italien",
    NO: "Italia",
    DK: "Italien",
    IE: "An Iodáil",
    GB: "Italy",
    IS: "Ítalía",
    RU: "Италия",
    TR: "İtalya",
    CY: "Ιταλία",
    MT: "Italja",
    LU: "Italien",
    XK: "Italia",
  },
  GR: { // Greece in different languages
    PT: "Grécia",
    ES: "Grecia",
    FR: "Grèce",
    BE: "Grèce",
    NL: "Griekenland",
    DE: "Griechenland",
    CH: "Griechenland",
    AT: "Griechenland",
    IT: "Grecia",
    SI: "Grčija",
    HR: "Grčka",
    BA: "Grčka",
    RS: "Grčka",
    ME: "Grčka",
    AL: "Greqi",
    MK: "Грција",
    GR: "Ελλάδα",
    BG: "Гърция",
    RO: "Grecia",
    MD: "Grecia",
    UA: "Греція",
    BY: "Грэцыя",
    PL: "Grecja",
    CZ: "Řecko",
    SK: "Grécko",
    HU: "Görögország",
    LT: "Graikija",
    LV: "Grieķija",
    EE: "Kreeka",
    FI: "Kreikka",
    SE: "Grekland",
    NO: "Hellas",
    DK: "Grækenland",
    IE: "An Ghréig",
    GB: "Greece",
    IS: "Grikkland",
    RU: "Греция",
    TR: "Yunanistan",
    CY: "Ελλάδα",
    MT: "Greċja",
    LU: "Griicheland",
    XK: "Greqia",
  },
  PL: { // Poland in different languages
    PT: "Polónia",
    ES: "Polonia",
    FR: "Pologne",
    BE: "Pologne",
    NL: "Polen",
    DE: "Polen",
    CH: "Polen",
    AT: "Polen",
    IT: "Polonia",
    SI: "Poljska",
    HR: "Poljska",
    BA: "Poljska",
    RS: "Poljska",
    ME: "Poljska",
    AL: "Poloni",
    MK: "Полска",
    GR: "Πολωνία",
    BG: "Полша",
    RO: "Polonia",
    MD: "Polonia",
    UA: "Польща",
    BY: "Польшча",
    PL: "Polska",
    CZ: "Polsko",
    SK: "Poľsko",
    HU: "Lengyelország",
    LT: "Lenkija",
    LV: "Polija",
    EE: "Poola",
    FI: "Puola",
    SE: "Polen",
    NO: "Polen",
    DK: "Polen",
    IE: "An Pholainn",
    GB: "Poland",
    IS: "Pólland",
    RU: "Польша",
    TR: "Polonya",
    CY: "Πολωνία",
    MT: "Polonja",
    LU: "Polen",
    XK: "Polonia",
  },
  NL: { // Netherlands in different languages
    PT: "Países Baixos",
    ES: "Países Bajos",
    FR: "Pays-Bas",
    BE: "Pays-Bas",
    NL: "Nederland",
    DE: "Niederlande",
    CH: "Niederlande",
    AT: "Niederlande",
    IT: "Paesi Bassi",
    SI: "Nizozemska",
    HR: "Nizozemska",
    BA: "Nizozemska",
    RS: "Holandija",
    ME: "Holandija",
    AL: "Holandë",
    MK: "Холандија",
    GR: "Ολλανδία",
    BG: "Нидерландия",
    RO: "Țările de Jos",
    MD: "Țările de Jos",
    UA: "Нідерланди",
    BY: "Нідэрланды",
    PL: "Holandia",
    CZ: "Nizozemsko",
    SK: "Holandsko",
    HU: "Hollandia",
    LT: "Nyderlandai",
    LV: "Nīderlande",
    EE: "Holland",
    FI: "Alankomaat",
    SE: "Nederländerna",
    NO: "Nederland",
    DK: "Nederlandene",
    IE: "An Ísiltír",
    GB: "Netherlands",
    IS: "Holland",
    RU: "Нидерланды",
    TR: "Hollanda",
    CY: "Ολλανδία",
    MT: "Pajjiżi l-Baxxi",
    LU: "Holland",
    XK: "Holanda",
  },
  IE: { // Ireland in different languages
    PT: "Irlanda",
    ES: "Irlanda",
    FR: "Irlande",
    BE: "Irlande",
    NL: "Ierland",
    DE: "Irland",
    CH: "Irland",
    AT: "Irland",
    IT: "Irlanda",
    SI: "Irska",
    HR: "Irska",
    BA: "Irska",
    RS: "Irska",
    ME: "Irska",
    AL: "Irlanda",
    MK: "Ирска",
    GR: "Ιρλανδία",
    BG: "Ирландия",
    RO: "Irlanda",
    MD: "Irlanda",
    UA: "Ірландія",
    BY: "Ірландыя",
    PL: "Irlandia",
    CZ: "Irsko",
    SK: "Írsko",
    HU: "Írország",
    LT: "Airija",
    LV: "Īrija",
    EE: "Iirimaa",
    FI: "Irlanti",
    SE: "Irland",
    NO: "Irland",
    DK: "Irland",
    IE: "Éire",
    GB: "Ireland",
    IS: "Írland",
    RU: "Ирландия",
    TR: "İrlanda",
    CY: "Ιρλανδία",
    MT: "Irlanda",
    LU: "Irland",
    XK: "Irlanda",
  },
  BE: { // Belgium in different languages
    PT: "Bélgica",
    ES: "Bélgica",
    FR: "Belgique",
    BE: "Belgique",
    NL: "België",
    DE: "Belgien",
    CH: "Belgien",
    AT: "Belgien",
    IT: "Belgio",
    SI: "Belgija",
    HR: "Belgija",
    BA: "Belgija",
    RS: "Belgija",
    ME: "Belgija",
    AL: "Belgjika",
    MK: "Белгија",
    GR: "Βέλγιο",
    BG: "Белгия",
    RO: "Belgia",
    MD: "Belgia",
    UA: "Бельгія",
    BY: "Бельгія",
    PL: "Belgia",
    CZ: "Belgie",
    SK: "Belgicko",
    HU: "Belgium",
    LT: "Belgija",
    LV: "Beļģija",
    EE: "Belgia",
    FI: "Belgia",
    SE: "Belgien",
    NO: "Belgia",
    DK: "Belgien",
    IE: "An Bheilg",
    GB: "Belgium",
    IS: "Belgía",
    RU: "Бельгия",
    TR: "Belçika",
    CY: "Βέλγιο",
    MT: "Belġju",
    LU: "Belsch",
    XK: "Belgjika",
  },
  LU: { // Luxembourg in different languages
    PT: "Luxemburgo",
    ES: "Luxemburgo",
    FR: "Luxembourg",
    BE: "Luxembourg",
    NL: "Luxemburg",
    DE: "Luxemburg",
    CH: "Luxemburg",
    AT: "Luxemburg",
    IT: "Lussemburgo",
    SI: "Luksemburg",
    HR: "Luksemburg",
    BA: "Luksemburg",
    RS: "Luksemburg",
    ME: "Luksemburg",
    AL: "Luksemburg",
    MK: "Луксембург",
    GR: "Λουξεμβούργο",
    BG: "Люксембург",
    RO: "Luxemburg",
    MD: "Luxemburg",
    UA: "Люксембург",
    BY: "Люксембург",
    PL: "Luksemburg",
    CZ: "Lucembursko",
    SK: "Luxembursko",
    HU: "Luxemburg",
    LT: "Liuksemburgas",
    LV: "Luksemburga",
    EE: "Luksemburg",
    FI: "Luxemburg",
    SE: "Luxemburg",
    NO: "Luxembourg",
    DK: "Luxembourg",
    IE: "Lucsamburg",
    GB: "Luxembourg",
    IS: "Lúxemborg",
    RU: "Люксембург",
    TR: "Lüksemburg",
    CY: "Λουξεμβούργο",
    MT: "Lussemburgu",
    LU: "Lëtzebuerg",
    XK: "Luksemburgu",
  },
  TR: { // Turkey in different languages
    PT: "Turquia",
    ES: "Turquía",
    FR: "Turquie",
    BE: "Turquie",
    NL: "Turkije",
    DE: "Türkei",
    CH: "Türkei",
    AT: "Türkei",
    IT: "Turchia",
    SI: "Turčija",
    HR: "Turska",
    BA: "Turska",
    RS: "Turska",
    ME: "Turska",
    AL: "Turqi",
    MK: "Турција",
    GR: "Τουρκία",
    BG: "Турция",
    RO: "Turcia",
    MD: "Turcia",
    UA: "Туреччина",
    BY: "Турцыя",
    PL: "Turcja",
    CZ: "Turecko",
    SK: "Turecko",
    HU: "Törökország",
    LT: "Turkija",
    LV: "Turcija",
    EE: "Türgi",
    FI: "Turkki",
    SE: "Turkiet",
    NO: "Tyrkia",
    DK: "Tyrkiet",
    IE: "An Tuirc",
    GB: "Turkey",
    IS: "Tyrkland",
    RU: "Турция",
    TR: "Türkiye",
    CY: "Τουρκία",
    MT: "Turkija",
    LU: "Tierkei",
    XK: "Turqia",
  },
  CY: { // Cyprus in different languages
    PT: "Chipre",
    ES: "Chipre",
    FR: "Chypre",
    BE: "Chypre",
    NL: "Cyprus",
    DE: "Zypern",
    CH: "Zypern",
    AT: "Zypern",
    IT: "Cipro",
    SI: "Ciper",
    HR: "Cipar",
    BA: "Kipar",
    RS: "Kipar",
    ME: "Kipar",
    AL: "Qipro",
    MK: "Кипар",
    GR: "Κύπρος",
    BG: "Кипър",
    RO: "Cipru",
    MD: "Cipru",
    UA: "Кіпр",
    BY: "Кіпр",
    PL: "Cypr",
    CZ: "Kypr",
    SK: "Cyprus",
    HU: "Ciprus",
    LT: "Kipras",
    LV: "Kipra",
    EE: "Küpros",
    FI: "Kypros",
    SE: "Cypern",
    NO: "Kypros",
    DK: "Cypern",
    IE: "An Chipir",
    GB: "Cyprus",
    IS: "Kýpur",
    RU: "Кипр",
    TR: "Kıbrıs",
    CY: "Κύπρος",
    MT: "Ċipru",
    LU: "Zypern",
    XK: "Qipro",
  },
  RU: { // Russia in different languages
    PT: "Rússia",
    ES: "Rusia",
    FR: "Russie",
    BE: "Russie",
    NL: "Rusland",
    DE: "Russland",
    CH: "Russland",
    AT: "Russland",
    IT: "Russia",
    SI: "Rusija",
    HR: "Rusija",
    BA: "Rusija",
    RS: "Rusija",
    ME: "Rusija",
    AL: "Rusi",
    MK: "Русија",
    GR: "Ρωσία",
    BG: "Русия",
    RO: "Rusia",
    MD: "Rusia",
    UA: "Росія",
    BY: "Расія",
    PL: "Rosja",
    CZ: "Rusko",
    SK: "Rusko",
    HU: "Oroszország",
    LT: "Rusija",
    LV: "Krievija",
    EE: "Venemaa",
    FI: "Venäjä",
    SE: "Ryssland",
    NO: "Russland",
    DK: "Rusland",
    IE: "An Rúis",
    GB: "Russia",
    IS: "Rússland",
    RU: "Россия",
    TR: "Rusya",
    CY: "Ρωσία",
    MT: "Russja",
    LU: "Russland",
    XK: "Rusia",
  },
  UA: { // Ukraine in different languages
    PT: "Ucrânia",
    ES: "Ucrania",
    FR: "Ukraine",
    BE: "Ukraine",
    NL: "Oekraïne",
    DE: "Ukraine",
    CH: "Ukraine",
    AT: "Ukraine",
    IT: "Ucraina",
    SI: "Ukrajina",
    HR: "Ukrajina",
    BA: "Ukrajina",
    RS: "Ukrajina",
    ME: "Ukrajina",
    AL: "Ukrainë",
    MK: "Украина",
    GR: "Ουκρανία",
    BG: "Украйна",
    RO: "Ucraina",
    MD: "Ucraina",
    UA: "Україна",
    BY: "Украіна",
    PL: "Ukraina",
    CZ: "Ukrajina",
    SK: "Ukrajina",
    HU: "Ukrajna",
    LT: "Ukraina",
    LV: "Ukraina",
    EE: "Ukraina",
    FI: "Ukraina",
    SE: "Ukraina",
    NO: "Ukraina",
    DK: "Ukraine",
    IE: "An Úcráin",
    GB: "Ukraine",
    IS: "Úkraína",
    RU: "Украина",
    TR: "Ukrayna",
    CY: "Ουκρανία",
    MT: "Ukrajna",
    LU: "Ukrain",
    XK: "Ukraina",
  },
  CZ: { // Czechia in different languages
    PT: "Chéquia",
    ES: "Chequia",
    FR: "Tchéquie",
    BE: "Tchéquie",
    NL: "Tsjechië",
    DE: "Tschechien",
    CH: "Tschechien",
    AT: "Tschechien",
    IT: "Cechia",
    SI: "Češka",
    HR: "Češka",
    BA: "Češka",
    RS: "Češka",
    ME: "Češka",
    AL: "Çeki",
    MK: "Чешка",
    GR: "Τσεχία",
    BG: "Чехия",
    RO: "Cehia",
    MD: "Cehia",
    UA: "Чехія",
    BY: "Чэхія",
    PL: "Czechy",
    CZ: "Česko",
    SK: "Česko",
    HU: "Csehország",
    LT: "Čekija",
    LV: "Čehija",
    EE: "Tšehhi",
    FI: "Tšekki",
    SE: "Tjeckien",
    NO: "Tsjekkia",
    DK: "Tjekkiet",
    IE: "An tSeicia",
    GB: "Czechia",
    IS: "Tékkland",
    RU: "Чехия",
    TR: "Çekya",
    CY: "Τσεχία",
    MT: "Iċ-Ċekja",
    LU: "Tschechien",
    XK: "Çekia",
  },
  HU: { // Hungary in different languages
    PT: "Hungria",
    ES: "Hungría",
    FR: "Hongrie",
    BE: "Hongrie",
    NL: "Hongarije",
    DE: "Ungarn",
    CH: "Ungarn",
    AT: "Ungarn",
    IT: "Ungheria",
    SI: "Madžarska",
    HR: "Mađarska",
    BA: "Mađarska",
    RS: "Mađarska",
    ME: "Mađarska",
    AL: "Hungari",
    MK: "Унгарија",
    GR: "Ουγγαρία",
    BG: "Унгария",
    RO: "Ungaria",
    MD: "Ungaria",
    UA: "Угорщина",
    BY: "Венгрыя",
    PL: "Węgry",
    CZ: "Maďarsko",
    SK: "Maďarsko",
    HU: "Magyarország",
    LT: "Vengrija",
    LV: "Ungārija",
    EE: "Ungari",
    FI: "Unkari",
    SE: "Ungern",
    NO: "Ungarn",
    DK: "Ungarn",
    IE: "An Ungáir",
    GB: "Hungary",
    IS: "Ungverjaland",
    RU: "Венгрия",
    TR: "Macaristan",
    CY: "Ουγγαρία",
    MT: "Ungerija",
    LU: "Ungarn",
    XK: "Hungaria",
  },
  SK: { // Slovakia in different languages
    PT: "Eslováquia",
    ES: "Eslovaquia",
    FR: "Slovaquie",
    BE: "Slovaquie",
    NL: "Slowakije",
    DE: "Slowakei",
    CH: "Slowakei",
    AT: "Slowakei",
    IT: "Slovacchia",
    SI: "Slovaška",
    HR: "Slovačka",
    BA: "Slovačka",
    RS: "Slovačka",
    ME: "Slovačka",
    AL: "Sllovaki",
    MK: "Словачка",
    GR: "Σλοβακία",
    BG: "Словакия",
    RO: "Slovacia",
    MD: "Slovacia",
    UA: "Словаччина",
    BY: "Славакія",
    PL: "Słowacja",
    CZ: "Slovensko",
    SK: "Slovensko",
    HU: "Szlovákia",
    LT: "Slovakija",
    LV: "Slovākija",
    EE: "Slovakkia",
    FI: "Slovakia",
    SE: "Slovakien",
    NO: "Slovakia",
    DK: "Slovakiet",
    IE: "An tSlóvaic",
    GB: "Slovakia",
    IS: "Slóvakía",
    RU: "Словакия",
    TR: "Slovakya",
    CY: "Σλοβακία",
    MT: "Slovakkja",
    LU: "Slowakei",
    XK: "Sllovakia",
  },
  SI: { // Slovenia in different languages
    PT: "Eslovénia",
    ES: "Eslovenia",
    FR: "Slovénie",
    BE: "Slovénie",
    NL: "Slovenië",
    DE: "Slowenien",
    CH: "Slowenien",
    AT: "Slowenien",
    IT: "Slovenia",
    SI: "Slovenija",
    HR: "Slovenija",
    BA: "Slovenija",
    RS: "Slovenija",
    ME: "Slovenija",
    AL: "Slloveni",
    MK: "Словенија",
    GR: "Σλοβενία",
    BG: "Словения",
    RO: "Slovenia",
    MD: "Slovenia",
    UA: "Словенія",
    BY: "Славенія",
    PL: "Słowenia",
    CZ: "Slovinsko",
    SK: "Slovinsko",
    HU: "Szlovénia",
    LT: "Slovėnija",
    LV: "Slovēnija",
    EE: "Sloveenia",
    FI: "Slovenia",
    SE: "Slovenien",
    NO: "Slovenia",
    DK: "Slovenien",
    IE: "An tSlóivéin",
    GB: "Slovenia",
    IS: "Slóvenía",
    RU: "Словения",
    TR: "Slovenya",
    CY: "Σλοβενία",
    MT: "Slovenja",
    LU: "Slowenien",
    XK: "Sllovenia",
  },
  HR: { // Croatia in different languages
    PT: "Croácia",
    ES: "Croacia",
    FR: "Croatie",
    BE: "Croatie",
    NL: "Kroatië",
    DE: "Kroatien",
    CH: "Kroatien",
    AT: "Kroatien",
    IT: "Croazia",
    SI: "Hrvaška",
    HR: "Hrvatska",
    BA: "Hrvatska",
    RS: "Hrvatska",
    ME: "Hrvatska",
    AL: "Kroaci",
    MK: "Хрватска",
    GR: "Κροατία",
    BG: "Хърватия",
    RO: "Croația",
    MD: "Croația",
    UA: "Хорватія",
    BY: "Харватыя",
    PL: "Chorwacja",
    CZ: "Chorvatsko",
    SK: "Chorvátsko",
    HU: "Horvátország",
    LT: "Kroatija",
    LV: "Horvātija",
    EE: "Horvaatia",
    FI: "Kroatia",
    SE: "Kroatien",
    NO: "Kroatia",
    DK: "Kroatien",
    IE: "An Chróit",
    GB: "Croatia",
    IS: "Króatía",
    RU: "Хорватия",
    TR: "Hırvatistan",
    CY: "Κροατία",
    MT: "Kroazja",
    LU: "Kroatien",
    XK: "Kroacia",
  },
  AL: { // Albania in different languages
    PT: "Albânia",
    ES: "Albania",
    FR: "Albanie",
    BE: "Albanie",
    NL: "Albanië",
    DE: "Albanien",
    CH: "Albanien",
    AT: "Albanien",
    IT: "Albania",
    SI: "Albanija",
    HR: "Albanija",
    BA: "Albanija",
    RS: "Albanija",
    ME: "Albanija",
    AL: "Shqipëria",
    MK: "Албанија",
    GR: "Αλβανία",
    BG: "Албания",
    RO: "Albania",
    MD: "Albania",
    UA: "Албанія",
    BY: "Албанія",
    PL: "Albania",
    CZ: "Albánie",
    SK: "Albánsko",
    HU: "Albánia",
    LT: "Albanija",
    LV: "Albānija",
    EE: "Albaania",
    FI: "Albania",
    SE: "Albanien",
    NO: "Albania",
    DK: "Albanien",
    IE: "An Albáin",
    GB: "Albania",
    IS: "Albanía",
    RU: "Албания",
    TR: "Arnavutluk",
    CY: "Αλβανία",
    MT: "Albanija",
    LU: "Albanien",
    XK: "Shqipëria",
  },
  AT: { // Austria in different languages
    PT: "Áustria",
    ES: "Austria",
    FR: "Autriche",
    BE: "Autriche",
    NL: "Oostenrijk",
    DE: "Österreich",
    CH: "Österreich",
    AT: "Österreich",
    IT: "Austria",
    SI: "Avstrija",
    HR: "Austrija",
    BA: "Austrija",
    RS: "Austrija",
    ME: "Austrija",
    AL: "Austri",
    MK: "Австрија",
    GR: "Αυστρία",
    BG: "Австрия",
    RO: "Austria",
    MD: "Austria",
    UA: "Австрія",
    BY: "Аўстрыя",
    PL: "Austria",
    CZ: "Rakousko",
    SK: "Rakúsko",
    HU: "Ausztria",
    LT: "Austrija",
    LV: "Austrija",
    EE: "Austria",
    FI: "Itävalta",
    SE: "Österrike",
    NO: "Østerrike",
    DK: "Østrig",
    IE: "An Ostair",
    GB: "Austria",
    IS: "Austurríki",
    RU: "Австрия",
    TR: "Avusturya",
    CY: "Αυστρία",
    MT: "Awstrija",
    LU: "Éisträich",
    XK: "Austri",
  },
  BG: { // Bulgaria in different languages
    PT: "Bulgária",
    ES: "Bulgaria",
    FR: "Bulgarie",
    BE: "Bulgarie",
    NL: "Bulgarije",
    DE: "Bulgarien",
    CH: "Bulgarien",
    AT: "Bulgarien",
    IT: "Bulgaria",
    SI: "Bolgarija",
    HR: "Bugarska",
    BA: "Bugarska",
    RS: "Bugarska",
    ME: "Bugarska",
    AL: "Bullgari",
    MK: "Бугарија",
    GR: "Βουλγαρία",
    BG: "България",
    RO: "Bulgaria",
    MD: "Bulgaria",
    UA: "Болгарія",
    BY: "Балгарыя",
    PL: "Bułgaria",
    CZ: "Bulharsko",
    SK: "Bulharsko",
    HU: "Bulgária",
    LT: "Bulgarija",
    LV: "Bulgārija",
    EE: "Bulgaaria",
    FI: "Bulgaria",
    SE: "Bulgarien",
    NO: "Bulgaria",
    DK: "Bulgarien",
    IE: "An Bhulgáir",
    GB: "Bulgaria",
    IS: "Búlgaría",
    RU: "Болгария",
    TR: "Bulgaristan",
    CY: "Βουλγαρία",
    MT: "Bulgarija",
    LU: "Bulgarien",
    XK: "Bullgaria",
  },
  RS: { // Serbia in different languages
    PT: "Sérvia",
    ES: "Serbia",
    FR: "Serbie",
    BE: "Serbie",
    NL: "Servië",
    DE: "Serbien",
    CH: "Serbien",
    AT: "Serbien",
    IT: "Serbia",
    SI: "Srbija",
    HR: "Srbija",
    BA: "Srbija",
    RS: "Србија",
    ME: "Srbija",
    AL: "Serbi",
    MK: "Србија",
    GR: "Σερβία",
    BG: "Сърбия",
    RO: "Serbia",
    MD: "Serbia",
    UA: "Сербія",
    BY: "Сербія",
    PL: "Serbia",
    CZ: "Srbsko",
    SK: "Srbsko",
    HU: "Szerbia",
    LT: "Serbija",
    LV: "Serbija",
    EE: "Serbia",
    FI: "Serbia",
    SE: "Serbien",
    NO: "Serbia",
    DK: "Serbien",
    IE: "An tSeirbia",
    GB: "Serbia",
    IS: "Serbía",
    RU: "Сербия",
    TR: "Sırbistan",
    CY: "Σερβία",
    MT: "Serbja",
    LU: "Serbien",
    XK: "Serbia",
  },
  BA: { // Bosnia and Herzegovina in different languages
    PT: "Bósnia e Herzegovina",
    ES: "Bosnia y Herzegovina",
    FR: "Bosnie-Herzégovine",
    BE: "Bosnie-Herzégovine",
    NL: "Bosnië en Herzegovina",
    DE: "Bosnien und Herzegowina",
    CH: "Bosnien und Herzegowina",
    AT: "Bosnien und Herzegowina",
    IT: "Bosnia ed Erzegovina",
    SI: "Bosna in Hercegovina",
    HR: "Bosna i Hercegovina",
    BA: "Bosna i Hercegovina",
    RS: "Bosna i Hercegovina",
    ME: "Bosna i Hercegovina",
    AL: "Bosnja dhe Hercegovina",
    MK: "Босна и Херцеговина",
    GR: "Βοσνία και Ερζεγοβίνη",
    BG: "Босна и Херцеговина",
    RO: "Bosnia și Herțegovina",
    MD: "Bosnia și Herțegovina",
    UA: "Боснія і Герцеговина",
    BY: "Боснія і Герцагавіна",
    PL: "Bośnia i Hercegowina",
    CZ: "Bosna a Hercegovina",
    SK: "Bosna a Hercegovina",
    HU: "Bosznia és Hercegovina",
    LT: "Bosnija ir Hercegovina",
    LV: "Bosnija un Hercegovina",
    EE: "Bosnia ja Hertsegoviina",
    FI: "Bosnia ja Hertsegovina",
    SE: "Bosnien och Hercegovina",
    NO: "Bosnia og Herzegovina",
    DK: "Bosnien-Hercegovina",
    IE: "An Bhoisnia agus Heirseagaivéin",
    GB: "Bosnia and Herzegovina",
    IS: "Bosnía og Hersegóvína",
    RU: "Босния и Герцеговина",
    TR: "Bosna-Hersek",
    CY: "Βοσνία και Ερζεγοβίνη",
    MT: "Bosnja u Ħerzegovina",
    LU: "Bosnien an Herzegowina",
    XK: "Bosnja dhe Hercegovina",
  },
  EE: { // Estonia in different languages
    PT: "Estónia",
    ES: "Estonia",
    FR: "Estonie",
    BE: "Estonie",
    NL: "Estland",
    DE: "Estland",
    CH: "Estland",
    AT: "Estland",
    IT: "Estonia",
    SI: "Estonija",
    HR: "Estonija",
    BA: "Estonija",
    RS: "Estonija",
    ME: "Estonija",
    AL: "Estoni",
    MK: "Естонија",
    GR: "Εσθονία",
    BG: "Естония",
    RO: "Estonia",
    MD: "Estonia",
    UA: "Естонія",
    BY: "Эстонія",
    PL: "Estonia",
    CZ: "Estonsko",
    SK: "Estónsko",
    HU: "Észtország",
    LT: "Estija",
    LV: "Igaunija",
    EE: "Eesti",
    FI: "Viro",
    SE: "Estland",
    NO: "Estland",
    DK: "Estland",
    IE: "An Eastóin",
    GB: "Estonia",
    IS: "Eistland",
    RU: "Эстония",
    TR: "Estonya",
    CY: "Εσθονία",
    MT: "Estonja",
    LU: "Estland",
    XK: "Estonia",
  },
  LV: { // Latvia in different languages
    PT: "Letónia",
    ES: "Letonia",
    FR: "Lettonie",
    BE: "Lettonie",
    NL: "Letland",
    DE: "Lettland",
    CH: "Lettland",
    AT: "Lettland",
    IT: "Lettonia",
    SI: "Latvija",
    HR: "Latvija",
    BA: "Latvija",
    RS: "Letonija",
    ME: "Letonija",
    AL: "Letoni",
    MK: "Летонија",
    GR: "Λετονία",
    BG: "Латвия",
    RO: "Letonia",
    MD: "Letonia",
    UA: "Латвія",
    BY: "Латвія",
    PL: "Łotwa",
    CZ: "Lotyšsko",
    SK: "Lotyšsko",
    HU: "Lettország",
    LT: "Latvija",
    LV: "Latvija",
    EE: "Läti",
    FI: "Latvia",
    SE: "Lettland",
    NO: "Latvia",
    DK: "Letland",
    IE: "An Laitvia",
    GB: "Latvia",
    IS: "Lettland",
    RU: "Латвия",
    TR: "Letonya",
    CY: "Λετονία",
    MT: "Latvja",
    LU: "Lettland",
    XK: "Letonia",
  },
  LT: { // Lithuania in different languages
    PT: "Lituânia",
    ES: "Lituania",
    FR: "Lituanie",
    BE: "Lituanie",
    NL: "Litouwen",
    DE: "Litauen",
    CH: "Litauen",
    AT: "Litauen",
    IT: "Lituania",
    SI: "Litva",
    HR: "Litva",
    BA: "Litva",
    RS: "Litvanija",
    ME: "Litvanija",
    AL: "Lituani",
    MK: "Литванија",
    GR: "Λιθουανία",
    BG: "Литва",
    RO: "Lituania",
    MD: "Lituania",
    UA: "Литва",
    BY: "Літва",
    PL: "Litwa",
    CZ: "Litva",
    SK: "Litva",
    HU: "Litvánia",
    LT: "Lietuva",
    LV: "Lietuva",
    EE: "Leedu",
    FI: "Liettua",
    SE: "Litauen",
    NO: "Litauen",
    DK: "Litauen",
    IE: "An Liotuáin",
    GB: "Lithuania",
    IS: "Litháen",
    RU: "Литва",
    TR: "Litvanya",
    CY: "Λιθουανία",
    MT: "Litwanja",
    LU: "Litauen",
    XK: "Lituania",
  },
  BY: { // Belarus in different languages
    PT: "Bielorrússia",
    ES: "Bielorrusia",
    FR: "Biélorussie",
    BE: "Biélorussie",
    NL: "Wit-Rusland",
    DE: "Belarus",
    CH: "Belarus",
    AT: "Belarus",
    IT: "Bielorussia",
    SI: "Belorusija",
    HR: "Bjelorusija",
    BA: "Bjelorusija",
    RS: "Belorusija",
    ME: "Belorusija",
    AL: "Bjellorusia",
    MK: "Белорусија",
    GR: "Λευκορωσία",
    BG: "Беларус",
    RO: "Belarus",
    MD: "Belarus",
    UA: "Білорусь",
    BY: "Беларусь",
    PL: "Białoruś",
    CZ: "Bělorusko",
    SK: "Bielorusko",
    HU: "Fehéroroszország",
    LT: "Baltarusija",
    LV: "Baltkrievija",
    EE: "Valgevene",
    FI: "Valko-Venäjä",
    SE: "Vitryssland",
    NO: "Hviterussland",
    DK: "Hviderusland",
    IE: "An Bhealarúis",
    GB: "Belarus",
    IS: "Hvíta-Rússland",
    RU: "Беларусь",
    TR: "Belarus",
    CY: "Λευκορωσία",
    MT: "Belarus",
    LU: "Wäissrussland",
    XK: "Bjellorusia",
  },
  MD: { // Moldova in different languages
    PT: "Moldávia",
    ES: "Moldavia",
    FR: "Moldavie",
    BE: "Moldavie",
    NL: "Moldavië",
    DE: "Moldau",
    CH: "Moldau",
    AT: "Moldau",
    IT: "Moldavia",
    SI: "Moldavija",
    HR: "Moldavija",
    BA: "Moldavija",
    RS: "Moldavija",
    ME: "Moldavija",
    AL: "Moldavi",
    MK: "Молдавија",
    GR: "Μολδαβία",
    BG: "Молдова",
    RO: "Moldova",
    MD: "Moldova",
    UA: "Молдова",
    BY: "Малдова",
    PL: "Mołdawia",
    CZ: "Moldavsko",
    SK: "Moldavsko",
    HU: "Moldova",
    LT: "Moldova",
    LV: "Moldova",
    EE: "Moldova",
    FI: "Moldova",
    SE: "Moldavien",
    NO: "Moldova",
    DK: "Moldova",
    IE: "An Mholdóiv",
    GB: "Moldova",
    IS: "Moldóva",
    RU: "Молдова",
    TR: "Moldova",
    CY: "Μολδαβία",
    MT: "Moldova",
    LU: "Moldawien",
    XK: "Moldavia",
  },
  NO: { // Norway in different languages
    PT: "Noruega",
    ES: "Noruega",
    FR: "Norvège",
    BE: "Norvège",
    NL: "Noorwegen",
    DE: "Norwegen",
    CH: "Norwegen",
    AT: "Norwegen",
    IT: "Norvegia",
    SI: "Norveška",
    HR: "Norveška",
    BA: "Norveška",
    RS: "Norveška",
    ME: "Norveška",
    AL: "Norvegji",
    MK: "Норвешка",
    GR: "Νορβηγία",
    BG: "Норвегия",
    RO: "Norvegia",
    MD: "Norvegia",
    UA: "Норвегія",
    BY: "Нарвегія",
    PL: "Norwegia",
    CZ: "Norsko",
    SK: "Nórsko",
    HU: "Norvégia",
    LT: "Norvegija",
    LV: "Norvēģija",
    EE: "Norra",
    FI: "Norja",
    SE: "Norge",
    NO: "Norge",
    DK: "Norge",
    IE: "An Iorua",
    GB: "Norway",
    IS: "Noregur",
    RU: "Норвегия",
    TR: "Norveç",
    CY: "Νορβηγία",
    MT: "Norveġja",
    LU: "Norwegen",
    XK: "Norvegjia",
  },
  SE: { // Sweden in different languages
    PT: "Suécia",
    ES: "Suecia",
    FR: "Suède",
    BE: "Suède",
    NL: "Zweden",
    DE: "Schweden",
    CH: "Schweden",
    AT: "Schweden",
    IT: "Svezia",
    SI: "Švedska",
    HR: "Švedska",
    BA: "Švedska",
    RS: "Švedska",
    ME: "Švedska",
    AL: "Suedi",
    MK: "Шведска",
    GR: "Σουηδία",
    BG: "Швеция",
    RO: "Suedia",
    MD: "Suedia",
    UA: "Швеція",
    BY: "Швецыя",
    PL: "Szwecja",
    CZ: "Švédsko",
    SK: "Švédsko",
    HU: "Svédország",
    LT: "Švedija",
    LV: "Zviedrija",
    EE: "Rootsi",
    FI: "Ruotsi",
    SE: "Sverige",
    NO: "Sverige",
    DK: "Sverige",
    IE: "An tSualainn",
    GB: "Sweden",
    IS: "Svíþjóð",
    RU: "Швеция",
    TR: "İsveç",
    CY: "Σουηδία",
    MT: "Żvezja",
    LU: "Schweden",
    XK: "Suedia",
  },
  FI: { // Finland in different languages
    PT: "Finlândia",
    ES: "Finlandia",
    FR: "Finlande",
    BE: "Finlande",
    NL: "Finland",
    DE: "Finnland",
    CH: "Finnland",
    AT: "Finnland",
    IT: "Finlandia",
    SI: "Finska",
    HR: "Finska",
    BA: "Finska",
    RS: "Finska",
    ME: "Finska",
    AL: "Finlandë",
    MK: "Финска",
    GR: "Φινλανδία",
    BG: "Финландия",
    RO: "Finlanda",
    MD: "Finlanda",
    UA: "Фінляндія",
    BY: "Фінляндыя",
    PL: "Finlandia",
    CZ: "Finsko",
    SK: "Fínsko",
    HU: "Finnország",
    LT: "Suomija",
    LV: "Somija",
    EE: "Soome",
    FI: "Suomi",
    SE: "Finland",
    NO: "Finland",
    DK: "Finland",
    IE: "An Fhionlainn",
    GB: "Finland",
    IS: "Finnland",
    RU: "Финляндия",
    TR: "Finlandiya",
    CY: "Φινλανδία",
    MT: "Finlandja",
    LU: "Finnland",
    XK: "Finlanda",
  },
  DK: { // Denmark in different languages
    PT: "Dinamarca",
    ES: "Dinamarca",
    FR: "Danemark",
    BE: "Danemark",
    NL: "Denemarken",
    DE: "Dänemark",
    CH: "Dänemark",
    AT: "Dänemark",
    IT: "Danimarca",
    SI: "Danska",
    HR: "Danska",
    BA: "Danska",
    RS: "Danska",
    ME: "Danska",
    AL: "Danimarka",
    MK: "Данска",
    GR: "Δανία",
    BG: "Дания",
    RO: "Danemarca",
    MD: "Danemarca",
    UA: "Данія",
    BY: "Данія",
    PL: "Dania",
    CZ: "Dánsko",
    SK: "Dánsko",
    HU: "Dánia",
    LT: "Danija",
    LV: "Dānija",
    EE: "Taani",
    FI: "Tanska",
    SE: "Danmark",
    NO: "Danmark",
    DK: "Danmark",
    IE: "An Danmhairg",
    GB: "Denmark",
    IS: "Danmörk",
    RU: "Дания",
    TR: "Danimarka",
    CY: "Δανία",
    MT: "Danimarka",
    LU: "Dänemark",
    XK: "Danimarka",
  },
  PT: { // Portugal in different languages
    PT: "Portugal",
    ES: "Portugal",
    FR: "Portugal",
    BE: "Portugal",
    NL: "Portugal",
    DE: "Portugal",
    CH: "Portugal",
    AT: "Portugal",
    IT: "Portogallo",
    SI: "Portugalska",
    HR: "Portugal",
    BA: "Portugal",
    RS: "Portugal",
    ME: "Portugal",
    AL: "Portugali",
    MK: "Португалија",
    GR: "Πορτογαλία",
    BG: "Португалия",
    RO: "Portugalia",
    MD: "Portugalia",
    UA: "Португалія",
    BY: "Партугалія",
    PL: "Portugalia",
    CZ: "Portugalsko",
    SK: "Portugalsko",
    HU: "Portugália",
    LT: "Portugalija",
    LV: "Portugāle",
    EE: "Portugal",
    FI: "Portugali",
    SE: "Portugal",
    NO: "Portugal",
    DK: "Portugal",
    IE: "An Phortaingéil",
    GB: "Portugal",
    IS: "Portúgal",
    RU: "Португалия",
    TR: "Portekiz",
    CY: "Πορτογαλία",
    MT: "Portugall",
    LU: "Portugal",
    XK: "Portugalia",
  },
  AD: { // Andorra in different languages
    PT: "Andorra",
    ES: "Andorra",
    FR: "Andorre",
    BE: "Andorre",
    NL: "Andorra",
    DE: "Andorra",
    CH: "Andorra",
    AT: "Andorra",
    IT: "Andorra",
    SI: "Andora",
    HR: "Andora",
    BA: "Andora",
    RS: "Andora",
    ME: "Andora",
    AL: "Andorra",
    MK: "Андора",
    GR: "Ανδόρα",
    BG: "Андора",
    RO: "Andorra",
    MD: "Andorra",
    UA: "Андорра",
    BY: "Андора",
    PL: "Andora",
    CZ: "Andorra",
    SK: "Andorra",
    HU: "Andorra",
    LT: "Andora",
    LV: "Andora",
    EE: "Andorra",
    FI: "Andorra",
    SE: "Andorra",
    NO: "Andorra",
    DK: "Andorra",
    IE: "Andóra",
    GB: "Andorra",
    IS: "Andorra",
    RU: "Андорра",
    TR: "Andorra",
    CY: "Ανδόρα",
    MT: "Andorra",
    LU: "Andorra",
    XK: "Andorra",
  },
  MC: { // Monaco in different languages
    PT: "Mónaco",
    ES: "Mónaco",
    FR: "Monaco",
    BE: "Monaco",
    NL: "Monaco",
    DE: "Monaco",
    CH: "Monaco",
    AT: "Monaco",
    IT: "Monaco",
    SI: "Monako",
    HR: "Monako",
    BA: "Monako",
    RS: "Monako",
    ME: "Monako",
    AL: "Monako",
    MK: "Монако",
    GR: "Μονακό",
    BG: "Монако",
    RO: "Monaco",
    MD: "Monaco",
    UA: "Монако",
    BY: "Манака",
    PL: "Monako",
    CZ: "Monako",
    SK: "Monako",
    HU: "Monaco",
    LT: "Monakas",
    LV: "Monako",
    EE: "Monaco",
    FI: "Monaco",
    SE: "Monaco",
    NO: "Monaco",
    DK: "Monaco",
    IE: "Monacó",
    GB: "Monaco",
    IS: "Mónakó",
    RU: "Монако",
    TR: "Monako",
    CY: "Μονακό",
    MT: "Monako",
    LU: "Monaco",
    XK: "Monako",
  },
  LI: { // Liechtenstein in different languages
    PT: "Listenstaine",
    ES: "Liechtenstein",
    FR: "Liechtenstein",
    BE: "Liechtenstein",
    NL: "Liechtenstein",
    DE: "Liechtenstein",
    CH: "Liechtenstein",
    AT: "Liechtenstein",
    IT: "Liechtenstein",
    SI: "Liechtenstein",
    HR: "Lihtenštajn",
    BA: "Lihtenštajn",
    RS: "Lihtenštajn",
    ME: "Lihtenštajn",
    AL: "Lihtenshtajn",
    MK: "Лихтенштајн",
    GR: "Λιχτενστάιν",
    BG: "Лихтенщайн",
    RO: "Liechtenstein",
    MD: "Liechtenstein",
    UA: "Ліхтенштейн",
    BY: "Ліхтэнштэйн",
    PL: "Liechtenstein",
    CZ: "Lichtenštejnsko",
    SK: "Lichtenštajnsko",
    HU: "Liechtenstein",
    LT: "Lichtenšteinas",
    LV: "Lihtenšteina",
    EE: "Liechtenstein",
    FI: "Liechtenstein",
    SE: "Liechtenstein",
    NO: "Liechtenstein",
    DK: "Liechtenstein",
    IE: "Lichtinstéin",
    GB: "Liechtenstein",
    IS: "Liechtenstein",
    RU: "Лихтенштейн",
    TR: "Lihtenştayn",
    CY: "Λιχτενστάιν",
    MT: "Liechtenstein",
    LU: "Liechtenstein",
    XK: "Lihtenshtajn",
  },
  SM: { // San Marino in different languages
    PT: "San Marino",
    ES: "San Marino",
    FR: "Saint-Marin",
    BE: "Saint-Marin",
    NL: "San Marino",
    DE: "San Marino",
    CH: "San Marino",
    AT: "San Marino",
    IT: "San Marino",
    SI: "San Marino",
    HR: "San Marino",
    BA: "San Marino",
    RS: "San Marino",
    ME: "San Marino",
    AL: "San Marino",
    MK: "Сан Марино",
    GR: "Άγιος Μαρίνος",
    BG: "Сан Марино",
    RO: "San Marino",
    MD: "San Marino",
    UA: "Сан-Марино",
    BY: "Сан-Марына",
    PL: "San Marino",
    CZ: "San Marino",
    SK: "San Marino",
    HU: "San Marino",
    LT: "San Marinas",
    LV: "Sanmarīno",
    EE: "San Marino",
    FI: "San Marino",
    SE: "San Marino",
    NO: "San Marino",
    DK: "San Marino",
    IE: "San Mairíne",
    GB: "San Marino",
    IS: "San Marínó",
    RU: "Сан-Марино",
    TR: "San Marino",
    CY: "Άγιος Μαρίνος",
    MT: "San Marino",
    LU: "San Marino",
    XK: "San Marino",
  },
  VA: { // Vatican City in different languages
    PT: "Cidade do Vaticano",
    ES: "Ciudad del Vaticano",
    FR: "Vatican",
    BE: "Vatican",
    NL: "Vaticaanstad",
    DE: "Vatikanstadt",
    CH: "Vatikanstadt",
    AT: "Vatikanstadt",
    IT: "Città del Vaticano",
    SI: "Vatikan",
    HR: "Vatikan",
    BA: "Vatikan",
    RS: "Vatikan",
    ME: "Vatikan",
    AL: "Qyteti i Vatikanit",
    MK: "Ватикан",
    GR: "Βατικανό",
    BG: "Ватикан",
    RO: "Vatican",
    MD: "Vatican",
    UA: "Ватикан",
    BY: "Ватыкан",
    PL: "Watykan",
    CZ: "Vatikán",
    SK: "Vatikán",
    HU: "Vatikán",
    LT: "Vatikanas",
    LV: "Vatikāns",
    EE: "Vatikan",
    FI: "Vatikaanivaltio",
    SE: "Vatikanstaten",
    NO: "Vatikanstaten",
    DK: "Vatikanstaten",
    IE: "Cathair na Vatacáine",
    GB: "Vatican City",
    IS: "Vatíkanið",
    RU: "Ватикан",
    TR: "Vatikan",
    CY: "Βατικανό",
    MT: "Belt il-Vatikan",
    LU: "Vatikanstad",
    XK: "Vatikani",
  },
  CH: { // Switzerland in different languages
    PT: "Suíça",
    ES: "Suiza",
    FR: "Suisse",
    BE: "Suisse",
    NL: "Zwitserland",
    DE: "Schweiz",
    CH: "Schweiz",
    AT: "Schweiz",
    IT: "Svizzera",
    SI: "Švica",
    HR: "Švicarska",
    BA: "Švicarska",
    RS: "Švajcarska",
    ME: "Švajcarska",
    AL: "Zvicra",
    MK: "Швајцарија",
    GR: "Ελβετία",
    BG: "Швейцария",
    RO: "Elveția",
    MD: "Elveția",
    UA: "Швейцарія",
    BY: "Швейцарыя",
    PL: "Szwajcaria",
    CZ: "Švýcarsko",
    SK: "Švajčiarsko",
    HU: "Svájc",
    LT: "Šveicarija",
    LV: "Šveice",
    EE: "Šveits",
    FI: "Sveitsi",
    SE: "Schweiz",
    NO: "Sveits",
    DK: "Schweiz",
    IE: "An Eilvéis",
    GB: "Switzerland",
    IS: "Sviss",
    RU: "Швейцария",
    TR: "İsviçre",
    CY: "Ελβετία",
    MT: "Svizzera",
    LU: "Schwäiz",
    XK: "Zvicra",
  },
  MK: { // North Macedonia in different languages
    PT: "Macedónia do Norte",
    ES: "Macedonia del Norte",
    FR: "Macédoine du Nord",
    BE: "Macédoine du Nord",
    NL: "Noord-Macedonië",
    DE: "Nordmazedonien",
    CH: "Nordmazedonien",
    AT: "Nordmazedonien",
    IT: "Macedonia del Nord",
    SI: "Severna Makedonija",
    HR: "Sjeverna Makedonija",
    BA: "Sjeverna Makedonija",
    RS: "Severna Makedonija",
    ME: "Sjeverna Makedonija",
    AL: "Maqedonia e Veriut",
    MK: "Северна Македонија",
    GR: "Βόρεια Μακεδονία",
    BG: "Северна Македония",
    RO: "Macedonia de Nord",
    MD: "Macedonia de Nord",
    UA: "Північна Македонія",
    BY: "Паўночная Македонія",
    PL: "Macedonia Północna",
    CZ: "Severní Makedonie",
    SK: "Severné Macedónsko",
    HU: "Észak-Macedónia",
    LT: "Šiaurės Makedonija",
    LV: "Ziemeļmaķedonija",
    EE: "Põhja-Makedoonia",
    FI: "Pohjois-Makedonia",
    SE: "Nordmakedonien",
    NO: "Nord-Makedonia",
    DK: "Nordmakedonien",
    IE: "An Mhacadóin Thuaidh",
    GB: "North Macedonia",
    IS: "Norður-Makedónía",
    RU: "Северная Македония",
    TR: "Kuzey Makedonya",
    CY: "Βόρεια Μακεδονία",
    MT: "Maċedonja ta' Fuq",
    LU: "Nordmazedonien",
    XK: "Maqedonia e Veriut",
  },
  ME: { // Montenegro in different languages
    PT: "Montenegro",
    ES: "Montenegro",
    FR: "Monténégro",
    BE: "Monténégro",
    NL: "Montenegro",
    DE: "Montenegro",
    CH: "Montenegro",
    AT: "Montenegro",
    IT: "Montenegro",
    SI: "Črna gora",
    HR: "Crna Gora",
    BA: "Crna Gora",
    RS: "Crna Gora",
    ME: "Crna Gora",
    AL: "Mali i Zi",
    MK: "Црна Гора",
    GR: "Μαυροβούνιο",
    BG: "Черна гора",
    RO: "Muntenegru",
    MD: "Muntenegru",
    UA: "Чорногорія",
    BY: "Чарнагорыя",
    PL: "Czarnogóra",
    CZ: "Černá Hora",
    SK: "Čierna Hora",
    HU: "Montenegró",
    LT: "Juodkalnija",
    LV: "Melnkalne",
    EE: "Montenegro",
    FI: "Montenegro",
    SE: "Montenegro",
    NO: "Montenegro",
    DK: "Montenegro",
    IE: "Montainéagró",
    GB: "Montenegro",
    IS: "Svartfjallaland",
    RU: "Черногория",
    TR: "Karadağ",
    CY: "Μαυροβούνιο",
    MT: "Montenegro",
    LU: "Montenegro",
    XK: "Mali i Zi",
  },
  XK: { // Kosovo in different languages
    PT: "Kosovo",
    ES: "Kosovo",
    FR: "Kosovo",
    BE: "Kosovo",
    NL: "Kosovo",
    DE: "Kosovo",
    CH: "Kosovo",
    AT: "Kosovo",
    IT: "Kosovo",
    SI: "Kosovo",
    HR: "Kosovo",
    BA: "Kosovo",
    RS: "Kosovo",
    ME: "Kosovo",
    AL: "Kosova",
    MK: "Косово",
    GR: "Κόσοβο",
    BG: "Косово",
    RO: "Kosovo",
    MD: "Kosovo",
    UA: "Косово",
    BY: "Косава",
    PL: "Kosowo",
    CZ: "Kosovo",
    SK: "Kosovo",
    HU: "Koszovó",
    LT: "Kosovas",
    LV: "Kosova",
    EE: "Kosovo",
    FI: "Kosovo",
    SE: "Kosovo",
    NO: "Kosovo",
    DK: "Kosovo",
    IE: "An Chosaiv",
    GB: "Kosovo",
    IS: "Kosovo",
    RU: "Косово",
    TR: "Kosova",
    CY: "Κόσοβο",
    MT: "Kosovo",
    LU: "Kosovo",
    XK: "Kosova",
  },
  GE: { // Georgia in different languages
    PT: "Geórgia",
    ES: "Georgia",
    FR: "Géorgie",
    BE: "Géorgie",
    NL: "Georgië",
    DE: "Georgien",
    CH: "Georgien",
    AT: "Georgien",
    IT: "Georgia",
    SI: "Gruzija",
    HR: "Gruzija",
    BA: "Gruzija",
    RS: "Gruzija",
    ME: "Gruzija",
    AL: "Gjeorgjia",
    MK: "Грузија",
    GR: "Γεωργία",
    BG: "Грузия",
    RO: "Georgia",
    MD: "Georgia",
    UA: "Грузія",
    BY: "Грузія",
    PL: "Gruzja",
    CZ: "Gruzie",
    SK: "Gruzínsko",
    HU: "Grúzia",
    LT: "Gruzija",
    LV: "Gruzija",
    EE: "Gruusia",
    FI: "Georgia",
    SE: "Georgien",
    NO: "Georgia",
    DK: "Georgien",
    IE: "An tSeoirsia",
    GB: "Georgia",
    IS: "Georgía",
    RU: "Грузия",
    TR: "Gürcistan",
    CY: "Γεωργία",
    MT: "Ġeorġja",
    LU: "Georgien",
    XK: "Gjeorgjia",
  },
  AM: { // Armenia in different languages
    PT: "Arménia",
    ES: "Armenia",
    FR: "Arménie",
    BE: "Arménie",
    NL: "Armenië",
    DE: "Armenien",
    CH: "Armenien",
    AT: "Armenien",
    IT: "Armenia",
    SI: "Armenija",
    HR: "Armenija",
    BA: "Armenija",
    RS: "Jermenija",
    ME: "Jermenija",
    AL: "Armeni",
    MK: "Ерменија",
    GR: "Αρμενία",
    BG: "Армения",
    RO: "Armenia",
    MD: "Armenia",
    UA: "Вірменія",
    BY: "Арменія",
    PL: "Armenia",
    CZ: "Arménie",
    SK: "Arménsko",
    HU: "Örményország",
    LT: "Armėnija",
    LV: "Armēnija",
    EE: "Armeenia",
    FI: "Armenia",
    SE: "Armenien",
    NO: "Armenia",
    DK: "Armenien",
    IE: "An Airméin",
    GB: "Armenia",
    IS: "Armenía",
    RU: "Армения",
    TR: "Ermenistan",
    CY: "Αρμενία",
    MT: "Armenja",
    LU: "Armenien",
    XK: "Armenia",
  },
  IS: { // Iceland in different languages
    PT: "Islândia",
    ES: "Islandia",
    FR: "Islande",
    BE: "Islande",
    NL: "IJsland",
    DE: "Island",
    CH: "Island",
    AT: "Island",
    IT: "Islanda",
    SI: "Islandija",
    HR: "Island",
    BA: "Island",
    RS: "Island",
    ME: "Island",
    AL: "Islanda",
    MK: "Исланд",
    GR: "Ισλανδία",
    BG: "Исландия",
    RO: "Islanda",
    MD: "Islanda",
    UA: "Ісландія",
    BY: "Ісландыя",
    PL: "Islandia",
    CZ: "Island",
    SK: "Island",
    HU: "Izland",
    LT: "Islandija",
    LV: "Islande",
    EE: "Island",
    FI: "Islanti",
    SE: "Island",
    NO: "Island",
    DK: "Island",
    IE: "An Íoslainn",
    GB: "Iceland",
    IS: "Ísland",
    RU: "Исландия",
    TR: "İzlanda",
    CY: "Ισλανδία",
    MT: "Islanda",
    LU: "Island",
    XK: "Islanda",
  },
  AZ: { // Azerbaijan in different languages
    PT: "Azerbaijão",
    ES: "Azerbaiyán",
    FR: "Azerbaïdjan",
    BE: "Azerbaïdjan",
    NL: "Azerbeidzjan",
    DE: "Aserbaidschan",
    CH: "Aserbaidschan",
    AT: "Aserbaidschan",
    IT: "Azerbaigian",
    SI: "Azerbajdžan",
    HR: "Azerbajdžan",
    BA: "Azerbajdžan",
    RS: "Azerbejdžan",
    ME: "Azerbejdžan",
    AL: "Azerbajxhan",
    MK: "Азербејџан",
    GR: "Αζερμπαϊτζάν",
    BG: "Азербайджан",
    RO: "Azerbaidjan",
    MD: "Azerbaidjan",
    UA: "Азербайджан",
    BY: "Азербайджан",
    PL: "Azerbejdżan",
    CZ: "Ázerbájdžán",
    SK: "Azerbajdžan",
    HU: "Azerbajdzsán",
    LT: "Azerbaidžanas",
    LV: "Azerbaidžāna",
    EE: "Aserbaidžaan",
    FI: "Azerbaidžan",
    SE: "Azerbajdzjan",
    NO: "Aserbajdsjan",
    DK: "Aserbajdsjan",
    IE: "An Asarbaiseáin",
    GB: "Azerbaijan",
    IS: "Aserbaídsjan",
    RU: "Азербайджан",
    TR: "Azerbaycan",
    CY: "Αζερμπαϊτζάν",
    MT: "Ażerbajġan",
    LU: "Aserbaidschan",
    XK: "Azerbajxhan",
  },
};

// Function to find country by name (case-insensitive, partial match)
export function findCountryByName(searchTerm) {
  const term = searchTerm.toLowerCase().trim();
  if (!term) return null;

  // First check English names
  for (const [code, data] of Object.entries(europeanCountries)) {
    if (data.name.toLowerCase().includes(term)) {
      return code;
    }
  }

  // Then check translations
  for (const [countryCode, translations] of Object.entries(countryTranslations)) {
    for (const translation of Object.values(translations)) {
      if (translation.toLowerCase().includes(term)) {
        return countryCode;
      }
    }
  }

  return null;
}

// Get all translations for a country code
export function getTranslationsForCountry(countryCode) {
  return countryTranslations[countryCode] || null;
}
